### ISSUE TITLE
Missing Cache/work-tracker-tile-state.pickle

### ISSUE THREAD

**Issue by multiburst** [martin-ueding/geo-activity-playground#274]
The NaN error #266  has been fixed - but now getting this when starting.

"no such file or directory: 'Cache/work-tracker-tile-state.pickle'"

```
"Importing new activities into database: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 844/844 [01:43<00:00,  8.12it/s]
Traceback (most recent call last):
  File "/home/micha/.local/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/micha/.local/pipx/venvs/geo-activity-playground/lib/python3.13/site-packages/geo_activity_playground/__main__.py", line 84, in main
    options.func(options)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/home/micha/.local/pipx/venvs/geo-activity-playground/lib/python3.13/site-packages/geo_activity_playground/__main__.py", line 50, in <lambda>
    func=lambda options: web_ui_main(
                         ~~~~~~~~~~~^
        options.basedir,
        ^^^^^^^^^^^^^^^^
    ...<2 lines>...
        port=options.port,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/micha/.local/pipx/venvs/geo-activity-playground/lib/python3.13/site-packages/geo_activity_playground/webui/app.py", line 102, in web_ui_main
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/micha/.local/pipx/venvs/geo-activity-playground/lib/python3.13/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 127, in scan_for_activities
    work_tracker_path("tile-state").unlink()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 746, in unlink
    os.unlink(self)
    ~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Cache/work-tracker-tile-state.pickle'
<sys>:0: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7b9fe18fec50>" 
```

**Comment by multiburst** [comment]
This is fixed now.

Probably by 0.42.2

@martin-ueding

**Comment by martin-ueding** [comment]
This isn't fixed, it just doesn't occur twice in the same base directory. I should still add that check.

**Comment by martin-ueding** [comment]
I've just released the fix with version 0.43.3.
